version: '3.9'

services:
  projectvr_database:
    container_name: ${PROJECTVR_DATABASE_CONTAINER_NAME}
    image: postgres:15.4
    ports:
      - "${PROJECTVR_DATABASE_EXTERNAL_PORT}:${PROJECTVR_DATABASE_INTERNAL_PORT}"
    volumes:
      - projectvrdb:/home/postgres/app/projectvrdb
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PROJECTVR_DATABASE_PASSWORD}
  
  projectvr_webapi:
    container_name: ${PROJECTVR_API_CONTAINER_NAME}
    image: projectvrwebapi
    ports:
      - "${PROJECTVR_API_EXTERNAL_PORT_HTTPS}:${PROJECTVR_API_INTERNAL_PORT_HTTPS}"
      - "${PROJECTVR_API_EXTERNAL_PORT_HTTP}:${PROJECTVR_API_INTERNAL_PORT_HTTP}"
    build:
      context: .
      dockerfile: ProjectVR.WebAPI/Dockerfile
    depends_on:
      - projectvr_database
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:${PROJECTVR_API_INTERNAL_PORT_HTTP}
      - Monitoring__SeqPort=${PROJECTVR_API_SEQ_INTERNAL_PORT}
      - Monitoring__SeqHost=${PROJECTVR_API_SEQ_CONTAINER_NAME}
      - ConnectionStrings__ProjectVRDbContext=Host=${PROJECTVR_DATABASE_CONTAINER_NAME};Port=${PROJECTVR_DATABASE_INTERNAL_PORT};Database=${PROJECTVR_DATABASE_NAME};Username=${PROJECTVR_DATABASE_USERNAME};Password=${PROJECTVR_DATABASE_PASSWORD};
  
  projectvr_seq:
    container_name: ${PROJECTVR_API_SEQ_CONTAINER_NAME}
    image: datalust/seq:latest
    ports:
      - "${PROJECTVR_API_SEQ_EXTERNAL_PORT}:${PROJECTVR_API_SEQ_INTERNAL_PORT}"
    depends_on:
      - projectvr_webapi
    restart: always
    environment:
      ACCEPT_EULA: "Y"
volumes:
  projectvrdb:    